version: "3.9"

services:
  llamacpp-server:
    image: ghcr.io/ggerganov/llama.cpp:server
    ports:
      - 8080:8080
    volumes:
      - ./llama.cpp/models:/models
    environment:
      LLAMA_ARG_MODEL: /models/llama-2-7b-chat.Q2_K.gguf
      LLAMA_ARG_CTX_SIZE: 4096
      LLAMA_ARG_N_PARALLEL: 2
      LLAMA_ARG_ENDPOINT_METRICS: 1
      LLAMA_ARG_PORT: 8080
    tty: true
    command: >
       -m models/llama-2-7b-chat.Q2_K.gguf -c 512 --host 0.0.0.0 --port 8080

  backend:
    build: ./backend
    volumes:
      - ./backend/app:/code/app
    ports:
      - 80:80
    depends_on: 
      - llamacpp-server
    tty: true
    command: >
       uvicorn app.main:app --host 0.0.0.0 --port 80